### ISSUE TITLE
brjs command global install

### ISSUE THREAD

**Issue by leggetter** [BladeRunnerJS/brjs#1]
Make `brjs` a globally installed command, where the apps and sdk live independently of each other.

To achieve this I'm assuming that the CLI commands may also need to be context-aware (#885) e.g. run `brjs create-blade` from within an application directory to create a Blade for an app

- [ ] - context aware commands - #885
- [x] - change BRJS.initialize so it no longer scans upwards to find the BRJS dir - #95
- [x] - update the BRJS.initialize() method to take two directories instead of one in preparation for making BladeRunnerJS a global command - see #93
- [x] - Allow BRJS to be run from outside of the SDK directory by putting brjs on the PATH - #1130
- [x] - allow apps to live seperately from the sdk - #1154

**Comment by andyberry88** [comment]
Apart from #885 which has been deprioritised, this has been completed and it's now possible to run `brjs` from the `PATH` and keep apps seperate from the SDK itself.
