### ISSUE TITLE
Support additional test runners via TestPlugin

### ISSUE THREAD

**Issue by leggetter** [BladeRunnerJS/brjs#8]
As covered in the [Model & Plugin Design](https://github.com/BladeRunnerJS/brjs/wiki/Model-And-Plugin-Design#plugin-interfaces-uml) and to facilitate #7 it would be great to support additional `TestPlugin` implementations.
- [ ] - create the ability for TestPlugins
- [ ] - change the current `test` command so it uses the plugins
- [ ] - create a `WebDriver` test plugin - #87
- [ ] - ensure the `WebDriver` plugin works with any browser and with absolute paths - #628
- [ ] - create a JSTD test plugin - #85
