### ISSUE TITLE
Issues to be fixed before next workshop

### ISSUE THREAD

**Issue by leggetter** [BladeRunnerJS/brjs#873]
1. [x] Simplified directory structure - #19 probably includes #2 (optional bladesets)
2. [ ] New dependencies aren't picked up - #866 
3. [ ] Better Blade templates - #865 
4. [ ] Improved test experience - #353 PhantomJS (#105 may be enough)
5. [ ] zero-config workbenches - #76 although we cleaning up the default workbench `index.html` would probably be a good enough start
6. [x] Help installing Java - #872
