### ISSUE TITLE
Fix several bugs in Topiarist

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#935]
Raising this issue here since the bugs themselves are in the Topiarist repo.

Things to fix:

- [x] - Bring isA in line with the rest of the methods - https://github.com/BladeRunnerJS/topiarist/issues/9
- [x] - Topiarist does not work in IE8 without es5-shim - https://github.com/BladeRunnerJS/topiarist/issues/10
- [x] - Error implementing interface in IE8 in a complex inheritance hierarchy - https://github.com/BladeRunnerJS/topiarist/issues/11
- [x] - Allow topiarist.implement() to appear at the top of the class definition - https://github.com/BladeRunnerJS/topiarist/issues/6.  This is related to #827 (br.implement does not work with classes that have aliases)
- [x] - Update browsers used in test - https://github.com/BladeRunnerJS/topiarist/issues/13

- [x] - Pull request, Cleanup the code so it conforms to the Caplin code style - https://github.com/BladeRunnerJS/topiarist/pull/14
- [x] - Pull requestr, Bugfix es5 shim - https://github.com/BladeRunnerJS/topiarist/pull/12

**Comment by avsmithy** [comment]
[Topiarist PR20](https://github.com/BladeRunnerJS/topiarist/pull/20) has been tested and merged.

[BRJS 1190/PR1194](https://github.com/BladeRunnerJS/brjs/pull/1194) has been tested and merged.

I can't see any other issues mentioned here that have not already been closed, so can we close this ticket?
