### ISSUE TITLE
[EPIC] Plugin Improvements

### ISSUE THREAD

**Issue by leggetter** [BladeRunnerJS/brjs#988]
We've probably broken down a number of issues too soon. So as part of going through the existing issues this one can be used to keep track of ideas and suggestions for plugin improvements that haven't been fully thought through.
- [ ] Better Plug in Development Experience. See #312 for Acceptance Criteria.
- [ ] create seed documentation for creating your own bundler (including tag support that will come later)
- [ ] create seed documentation for creating model observer plugins
- [ ] create seed documentation for the create() and populate() methods
- [ ] create seed documentation for model navigation
- [ ] review class/method access control and package structure. See #66
- [ ] create API docs for all model code and plugin interfaces (Java). See #67
- [ ] Bundler User Guide and Tutorial
- [ ] write BRJS model user guides
- [ ] add website and API docs about plugins and logging. See #773 
- [ ] rename conf/java to conf/plugins (or similar). See #806 
- [ ] clean up the plugin APIs and make them as simple as possible
