### ISSUE TITLE
[EPIC] dashboard improvements

### ISSUE THREAD

**Issue by andy-berry-dev** [BladeRunnerJS/brjs#998]
The dashboard needs to be bladified/rewritten.

We've also had a number of other issues raised that should be done as part of the bladifying/rewrite.
- [ ] - split up dashboard app so it uses multiple blades #328
- [ ] - list aspects in the dashboard #647
- [ ] - It should be possible to create Aspects via the web dashboard #748
- [ ] - Cannot create a blade or bladeset with 2 letters via the dashboard #991
- [ ] - Improve experience of running tests from the dashboard #840
- [ ] - Cannot import blades from another app's 'default' bladeset #992
